const INCREMENT = 'INCREMENT';
const INCREMENT_IF_ODD = 'INCREMENT_IF_ODD';
const DECREMENT = 'DECREMENT';
const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';

export default {
  INCREMENT,
  INCREMENT_IF_ODD,
  DECREMENT,
  RECEIVE_ARTICLES,
  REQUEST_ARTICLES
}