export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
export const REQUEST_ADD_ARTICLE = 'REQUEST_ADD_ARTICLE';
export const SUCCESS_ADD_ARTICLE = 'SUCCESS_ADD_ARTICLE';
export const FAILURE_ADD_ARTICLE = 'FAILURE_ADD_ARTICLE';