const INCREMENT = 'INCREMENT';
const INCREMENT_IF_ODD = 'INCREMENT_IF_ODD';
const DECREMENT = 'DECREMENT';
const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
const REQUEST_ADD_ARTICLE = 'REQUEST_ADD_ARTICLE';
const SUCCESS_ADD_ARTICLE = 'SUCCESS_ADD_ARTICLE';
const FAILURE_ADD_ARTICLE = 'FAILURE_ADD_ARTICLE';

export default {
  INCREMENT,
  INCREMENT_IF_ODD,
  DECREMENT,
  RECEIVE_ARTICLES,
  REQUEST_ARTICLES,
  REQUEST_ADD_ARTICLE,
  SUCCESS_ADD_ARTICLE,
  FAILURE_ADD_ARTICLE
}